apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-manager
  name: task-manager
spec:
  ports:
  - name: 80-5000
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: task-manager
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
